basePath: /
host: 0.0.0.0:8000
info:
  contact:
    email: narek.seinyan@gmail.com
    name: API Support
    url: http://seinyan.ru
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger API
  version: "1.0"
paths: {}
swagger: "2.0"
